### ISSUE TITLE
Error: Continuation section too long

### ISSUE THREAD

**Issue by eglacias** [BashTux1/AutoCorrect-AHK-2.0#3]
would love to get this working, not much of a programmer but maybe the said section can be broken up or i dunno whats happening...

---------------------------
AutoCorrect_2.0.ahk
---------------------------
Error at line 1.

Line Text: <meta name="optimizely-datafile" content="{&quot;version&quot;: &quot;4&quot;, &quot;rollouts&quot;:...
Error: Continuation section too long.

The program will exit.
---------------------------
OK   
---------------------------

**Comment by BashTux1** [comment]
> would love to get this working, not much of a programmer but maybe the said section can be broken up or i dunno whats happening...
> 
> ## AutoCorrect_2.0.ahk
> Error at line 1.
> 
> Line Text: <meta name="optimizely-datafile" content="{"version": "4", "rollouts":...
> Error: Continuation section too long.
> 
> ## The program will exit.
> ## OK

I'm not sure what's going on, on your end.
This script is working fine on my side. I actually run the github hosted file to ensure it all works.

What version of AutoHotkey have you installed? (works with v1.1.33.02, has NOT been tested with v2 Alpha)

If you "Download Current Version" you should end up with the correct version as stated above.

**Comment by eglacias** [comment]
well even my own scripts wouldnt work with AutoHotkey_1.1.33.02_setup.exe
neither would your script
i had to go back to AutoHotkey_1.1.31.00_setup.exe
to run my own scripts even, all later failed.

i tried yours unsuccessfully all the way back to AutoHotkey112207_Install.exe

downloaded from https://github.com/BashTux1/AutoCorrect-AHK-2.0/find/main

**Comment by ubikq** [comment]
I suspect the issue is that the downloaded file does not contain the script itself but HTML code.
I was able to replicate the issue by right clicking the AutoCorrect_2.0.ahk link and saving. The saved AutoCorrect_2.0.ahk file contains HTML code which causes the same issue.

To solve the problem, click on the "CODE" button and choose "Download ZIP" to download all of the files in the repository. The AutoCorrect_2.0.ahk file contained within the ZIP file should work fine.

**Comment by BashTux1** [comment]
> I suspect the issue is that the downloaded file does not contain the script itself but HTML code.
> I was able to replicate the issue by right clicking the AutoCorrect_2.0.ahk link and saving. The saved AutoCorrect_2.0.ahk file contains HTML code which causes the same issue.
> 
> To solve the problem, click on the "CODE" button and choose "Download ZIP" to download all of the files in the repository. The AutoCorrect_2.0.ahk file contained within the ZIP file should work fine.

This seems to be spot on (I have the same results when direclty right clicking and downloading the file), if you are right clicking the flie and saving it, Github does not seem to download the file but rather an HTML representaion of it.

The best method to download the file is to use the "Code" button and then download the zip file which will download the repo in its entirty with all files as intended.

Thanks @ubikq for spotting this. I usually clone the repo directly via the github desktop app in windows and therefore have not run into this before.

**Comment by eglacias** [comment]
yep that did it... thanks!
